[package]
name = "zed-http-core"
version = "0.4.8"
edition = "2021"
rust-version = "1.74"

[dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
regex = "1"
chrono = { version = "0.4", features = ["serde"] }
indexmap = { version = "2", features = ["serde"] }
url = "2"
uuid = { version = "1", features = ["v7"] }
rand = "0.8"
base64 = "0.22"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
