id = "http-client"
name = "HTTP Client"
version = "0.4.6"
schema_version = 1
authors = ["Paul Snow <bovinemagnet@gmail.com>"]
description = "Run IntelliJ-compatible HTTP and GraphQL request files from Zed"
repository = "https://github.com/bovinemagnet/zed-http-client"
languages = ["languages/http-request"]

[grammars.http_request]
repository = "https://github.com/bovinemagnet/tree-sitter-http-request"
rev = "d58c11feca5635f1f556d8771be70a2dc5d76430"
